# Generated by Django 3.1.4 on 2020-12-27 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_order_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
