# Generated by Django 3.1.4 on 2020-12-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20201228_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promo',
        ),
        migrations.DeleteModel(
            name='Promo',
        ),
    ]
