# Generated by Django 3.1.4 on 2020-12-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_promo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promo',
        ),
    ]
