# Generated by Django 3.1.4 on 2020-12-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_order_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='promo_discount',
            field=models.FloatField(),
        ),
    ]
