# Generated by Django 3.1.4 on 2020-12-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20201228_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promo',
        ),
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.ManyToManyField(to='catalog.Promo'),
        ),
    ]
