# Generated by Django 3.1.4 on 2020-12-28 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
