# Generated by Django 3.1.4 on 2020-12-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_remove_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state_option',
            field=models.CharField(choices=[('SA', 'Santo Domingo'), ('SE', 'Santo Domingo Este'), ('SO', 'Santo Domingo Oeste'), ('SN', 'Santo Domingo Norte')], max_length=2),
        ),
    ]
