# Generated by Django 3.1.4 on 2020-12-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20201229_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'Casual'), ('F', 'Formal')], max_length=2),
        ),
    ]
